---
# tasks file for slack-deploy/
- include: slack_elb.yaml
  when: ec2_load_balancer is defined and aws_resource_tags.VREnv ==  PROD

- include: slack_no_elb.yaml
  when: ec2_load_balancer is not defined and aws_resource_tags.VREnv == PROD