- name: Send notification message via Slack (ELB)
  local_action:
    module: slack
    token: "{{ slack_token }}"
    msg: |
      @channel: your environment are waiting for deploy.
      You can open your new <http://{{ aws_elb_dns_name }}>
      to verify if everthing it's ok. Finally you can run
      @deploy_bot: deploy {{ aws_elb_dns_name }} ABC-DEF-GHI
    channel: "#{{ slack_channel_notify }}"
    username: "{{ slack_username }}"

#Finally you can run
      #@deploy_bot: deploy {{ response_deploy.json.cname_dns }} {{ response_deploy.json.uuid }}